version: "3.8"

networks:
  php_advanced:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.30
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql
    ports:
      - 33066:3306
    networks:
      - php_advanced

  adminer:
    image: adminer
    restart: always
    ports:
      - 8880:8080
    container_name: admin_panel
    networks:
      - php_advanced

  php:
    build:
      context: .docker/php
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - 8081:80
    container_name: php
    networks:
      - php_advanced