FROM php:8.1-apache

RUN apt-get update && apt-get install -y \
      libpq-dev && \
      docker-php-ext-install pdo_pgsql

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer